import fs from 'node:fs/promises';
import path from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';

const skillLibrary = path.join(homedir(), '.agents/skills/chrome-devtools/scripts/lib/browser.js');
const { getBrowser, getPage, closeBrowser } = await import(pathToFileURL(skillLibrary).href);

const output = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../docs/screenshots');
await fs.mkdir(output, { recursive: true });
const desktop = { width: Number(process.env.VECTOR_QA_WIDTH || 1440), height: Number(process.env.VECTOR_QA_HEIGHT || 900) };
const browser = await getBrowser({ headless: true, viewport: desktop, args: ['--enable-unsafe-swiftshader'] });
const page = await getPage(browser);
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle2' });
await page.waitForFunction(() => !!window.__VECTOR99__);
await page.screenshot({ path: `${output}/title.png` });
await page.click('#help-button');
await page.waitForSelector('#help-dialog[open]');
await page.screenshot({ path: `${output}/briefing.png` });
await page.click('[data-close="help-dialog"]');
await page.click('#start-button');
await page.waitForFunction(() => window.__VECTOR99__.snapshot().phase === 'racing');
await page.keyboard.down('w');
await page.waitForFunction(()=>window.__VECTOR99__.snapshot().ships[0].speed>=139,{timeout:20000});
await page.keyboard.up('w');
const driven = await page.evaluate(() => window.__VECTOR99__.snapshot());
await page.screenshot({ path: `${output}/race.png` });
await page.keyboard.press('Space');
await new Promise(resolve => setTimeout(resolve, 80));
const itemUsed = await page.evaluate(() => ({item:window.__VECTOR99__.snapshot().ships[0].item,notice:document.getElementById('notice').textContent}));
const steerBefore=await page.evaluate(()=>({x:window.__VECTOR99__.snapshot().ships[0].x,time:window.__VECTOR99__.snapshot().elapsed}));
await page.keyboard.down('d');
await page.waitForFunction(time=>window.__VECTOR99__.snapshot().elapsed>time+.2,{},steerBefore.time);
await page.keyboard.up('d');
const steered = await page.evaluate(() => window.__VECTOR99__.snapshot().ships[0].x);
await page.keyboard.press('Escape');
await page.waitForSelector('#pause-overlay:not([hidden])');
const pauseBefore = await page.evaluate(() => window.__VECTOR99__.snapshot().elapsed);
await new Promise(resolve => setTimeout(resolve, 500));
const pauseAfter = await page.evaluate(() => window.__VECTOR99__.snapshot().elapsed);
await page.click('#resume-button');
await page.click('#settings-button');
await page.click('#bloom');
await page.click('#bloom');
await page.select('#camera-roll','0');
await page.click('#settings-done-button');
await page.waitForFunction(() => window.__VECTOR99__.snapshot().phase === 'racing');
const resumeBefore = await page.evaluate(()=>window.__VECTOR99__.snapshot().ships[0].speed);
const resumeTime = await page.evaluate(()=>window.__VECTOR99__.snapshot().elapsed);
await page.keyboard.down('w');
await page.waitForFunction(time=>window.__VECTOR99__.snapshot().elapsed>time+.3,{},resumeTime);
await page.keyboard.up('w');
const resumeAfter = await page.evaluate(()=>window.__VECTOR99__.snapshot().ships[0].speed);
await page.keyboard.press('Escape');
await page.click('#quit-button');
await page.setViewport({ width: 390, height: 844 });
await page.screenshot({ path: `${output}/mobile-title.png` });
const mobileLayout = await page.evaluate(() => ({ width:innerWidth, scroll:document.documentElement.scrollWidth, start:document.getElementById('start-button').getBoundingClientRect().toJSON() }));
await page.setViewport(desktop);
const sections=[];
for(const section of ['bank','halfpipe','launch','bowl']){
  await page.goto(`http://127.0.0.1:5173/?preview=${section}`,{waitUntil:'networkidle2'});
  await page.keyboard.down('w');
  await new Promise(resolve=>setTimeout(resolve,section==='launch'?900:250));
  await page.screenshot({path:`${output}/${section}.png`});
  await page.keyboard.up('w');
  sections.push({section,state:await page.evaluate(()=>window.__VECTOR99__.snapshot())});
}
await page.goto('http://127.0.0.1:5173/?preview=boost',{waitUntil:'networkidle2'});
await page.keyboard.down('w');
await page.keyboard.press('Space');
await page.waitForFunction(()=>window.__VECTOR99__.snapshot().ships[0].speed>145&&window.__VECTOR99__.snapshot().trailVertices>200);
await page.screenshot({path:`${output}/boost-trails.png`});
const boostEffects=await page.evaluate(()=>window.__VECTOR99__.snapshot());
await page.keyboard.up('w');
await page.keyboard.press('Escape');
const effectsBefore=await page.evaluate(()=>window.__VECTOR99__.snapshot());
await new Promise(resolve=>setTimeout(resolve,350));
const effectsAfter=await page.evaluate(()=>window.__VECTOR99__.snapshot());
const effectsPauseStable=effectsBefore.trailVertices===effectsAfter.trailVertices&&effectsBefore.particles===effectsAfter.particles;
await page.goto('http://127.0.0.1:5173/?preview=launch',{waitUntil:'domcontentloaded'});
await page.keyboard.down('w');
await page.waitForFunction(()=>window.__VECTOR99__.snapshot().ships[0].airborne>.1);
await page.screenshot({path:`${output}/hover-flight.png`});
const flight=await page.evaluate(()=>window.__VECTOR99__.snapshot().ships[0]);
await page.waitForFunction(()=>window.__VECTOR99__.snapshot().ships[0].airborne===0);
const landing=await page.evaluate(()=>window.__VECTOR99__.snapshot().ships[0]);
await page.keyboard.up('w');
await page.goto('http://127.0.0.1:5173/?preview=finish',{waitUntil:'networkidle2'});
await page.keyboard.down('w');
await page.waitForSelector('#results-overlay:not([hidden])');
await page.keyboard.up('w');
const finish=await page.evaluate(()=>({phase:window.__VECTOR99__.snapshot().phase,laps:window.__VECTOR99__.snapshot().ships[0].laps,rows:document.querySelectorAll('.result-row').length}));
await page.screenshot({path:`${output}/results.png`});
await page.click('#race-again-button');
const reset=await page.evaluate(()=>window.__VECTOR99__.snapshot());
// Item activation is verified with the known held booster below. A normal race
// can acquire a new item between the Space press and the next sampled frame.
const success=errors.length===0&&driven.ships[0].speed>120&&steered>steerBefore.x&&pauseBefore===pauseAfter&&resumeAfter>resumeBefore&&finish.laps===3&&reset.ships[0].laps===0&&boostEffects.trailVertices>200&&boostEffects.particles>0&&boostEffects.ships[0].boost>0&&effectsPauseStable&&flight.airHeight>1&&landing.airborne===0;
console.log(JSON.stringify({success,errors,driven:{player:driven.ships[0],rivals:driven.ships.slice(1).map(s=>({id:s.id,speed:s.speed,aiPace:s.aiPace}))},itemUsed,steered,pauseStable:pauseBefore===pauseAfter,resumeBefore,resumeAfter,finish,restarted:reset.phase==='countdown'&&reset.ships[0].laps===0,mobileLayout,boostEffects:{speed:boostEffects.ships[0].speed,trailVertices:boostEffects.trailVertices,particles:boostEffects.particles},effectsPauseStable,flight,landing,sections:sections.map(s=>({section:s.section,player:s.state.ships[0],drawCalls:s.state.drawCalls})),screenshots:['title.png','briefing.png','race.png','mobile-title.png','bank.png','halfpipe.png','launch.png','bowl.png','results.png','boost-trails.png','hover-flight.png']},null,2));
await closeBrowser();
if(!success)process.exitCode=1;
